FROM ruby:3.3.1-alpine

RUN apk update -qq && apk add libpq-dev nodejs vim g++ make git postgresql-dev tzdata
RUN apk add --no-cache gcompat

WORKDIR /workspace

ADD ../Gemfile /workspace/Gemfile

ADD ../Gemfile.lock /workspace/Gemfile.lock

RUN gem install bundler -v 2.4.19
RUN bundle install

COPY . .

CMD [ "rails", "s", "-b", "0.0.0.0" ]