version: '3.9'
services:
  app:
    container_name: se_app_container
    build:
      dockerfile: ./.docker/app/dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DEV_DATABASE: ${POSTGRES_DEV_DATABASE}
      POSTGRES_TEST_DATABASE: ${POSTGRES_TEST_DATABASE}
      POSTGRES_PRO_DATABASE: ${POSTGRES_PROD_DATABASE}
    volumes:
      - .:/workspace
    tty: true
    stdin_open: true
    ports:
      - 3000:3000

  db:
    container_name: se_db_container
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - se-db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_ALLOW_EMPTY_PASSWORD: "yes"
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DEV_DATABASE: ${POSTGRES_DEV_DATABASE}

  # sidekiq:
  #   container_name: se_sidekiq_container
  #   build:
  #     context: ./.docker/sidekiq/Dockerfile
  #   volumes:
  #     - .:/workspace
  #   depends_on:
  #     - redis

  redis:
    container_name: se_redis_container
    image: redis:7.2.4
    env_file: .env
    command: redis-server --appendonly yes
    ports:
      - 6379:6379

volumes:
  se-db-volume: